# general
gpu_id: 0
use_gpu: True
seed: [999]
data_path: 'data/'
preprocessed_data: 'train data/'
preprocessed_data_splitting: 'x_label'
load_preprocessed: True
checkpoint_dir: 'saved'
save_recommended_topk: True
recommend_topk: 'recommend_topk/'

embedding_size: 64

# training settings
epochs: 1000
train_batch_size: 2048
learner: adam
learning_rate: 0.0001
training_neg_sample_num: 1
use_neg_sampling: True
use_full_sampling: False
eval_step: 1
stopping_step: 50

min_piRNA_inter_num: 1
min_disease_inter_num: 1
max_piRNA_inter_num: ~
max_disease_inter_num: ~
PIRNA_ID_FIELD: piRNA_id:token
DISEASE_ID_FIELD: disease_id:token
TIME_FIELD: timestamp:float
load_cols: [piRNA_id:token, disease_id:token, timestamp:float]
field_separator: "\t"

NEG_PREFIX: neg__

# evaluation settings
split_ratio: [0.7,0.1,0.2]
metrics: ["Recall", "NDCG", "MAP", "Precision"]
topk: [5, 10]
valid_metric: Recall@10
eval_batch_size: 4096

# iteration parameters
hyper_parameters: ["seed"]

